"""Resolution of the ffmpeg/ffprobe binaries to use.

Keeping this in one place stops the GUI from probing with one build while the
conversion runs with another. Lookup order:

1. the ``ffmpeg_executable`` / ``ffprobe_executable`` environment variable
   (also what the conversion script honours);
2. inside an AppImage, the bundled build — either ``$APPDIR/usr/bin`` or the
   ``usr/bin`` next to this module, which is where the AppRun generated by
   appimage-creator puts it (it prepends ``$HERE/usr/bin`` to PATH and does not
   rely on APPDIR);
3. jellyfin-ffmpeg, matching the conversion script's preference;
4. the install prefix of this application (``/usr/local`` builds and the like);
5. PATH.

Nothing here is mandatory: when no binary is found the plain name is returned,
so the host's ffmpeg on PATH is used exactly like before.
"""

import os
import shutil

_JELLYFIN_DIR = "/usr/lib/jellyfin-ffmpeg"


def _running_from_appimage() -> bool:
    """Same check constants.py uses to locate the conversion script."""
    return "APPIMAGE" in os.environ or "APPDIR" in os.environ


def _prefix_candidate(name: str) -> str:
    """<prefix>/share/big-video-converter/utils/ -> <prefix>/bin/<name>."""
    module_dir = os.path.dirname(os.path.abspath(__file__))
    prefix = os.path.abspath(os.path.join(module_dir, "..", "..", ".."))
    return os.path.join(prefix, "bin", name)


def _bundled_candidates(name: str):
    """Locations of a binary shipped inside the AppImage, if any."""
    if not _running_from_appimage():
        return []

    candidates = []
    appdir = os.environ.get("APPDIR")
    if appdir:
        candidates.append(os.path.join(appdir, "usr", "bin", name))
    candidates.append(_prefix_candidate(name))
    return candidates


def _resolve(name: str, env_var: str) -> str:
    override = os.environ.get(env_var)
    if override and (os.path.isabs(override) or shutil.which(override)):
        return override

    # A build shipped in the AppImage wins over anything on the host.
    for candidate in _bundled_candidates(name):
        if os.access(candidate, os.X_OK):
            return candidate

    jellyfin = os.path.join(_JELLYFIN_DIR, name)
    if os.access(jellyfin, os.X_OK):
        return jellyfin

    prefix_candidate = _prefix_candidate(name)
    if os.access(prefix_candidate, os.X_OK):
        return prefix_candidate

    return shutil.which(name) or name


def get_ffmpeg_executable() -> str:
    """Path (or name) of the ffmpeg binary to use."""
    return _resolve("ffmpeg", "ffmpeg_executable")


def get_ffprobe_executable() -> str:
    """Path (or name) of the ffprobe binary to use."""
    return _resolve("ffprobe", "ffprobe_executable")
